#!/usr/bin/env python3
"""
Kconfig to Ada Package Generator

Converts Zephyr's autoconf.h (Kconfig output) to an Ada package with
type-safe constants, eliminating the need for C preprocessor directives
in Ada code.

Usage:
    python3 kconfig_to_ada.py --input autoconf.h --output zephyr_config.ads
"""

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple, Optional


class ConfigEntry:
    """Represents a single Kconfig entry"""
    def __init__(self, name: str, value: str, is_bool: bool = False):
        self.name = name
        self.value = value
        self.is_bool = is_bool

    def to_ada_constant(self) -> str:
        """Convert to Ada constant declaration"""
        # Convert CONFIG_FOO_BAR to Foo_Bar (Ada naming convention)
        ada_name = self._to_ada_name(self.name)

        if self.is_bool:
            ada_value = "True" if self.value == "1" else "False"
            return f"   {ada_name} : constant Boolean := {ada_value};"
        elif self.value.startswith('"') and self.value.endswith('"'):
            # String constant
            return f"   {ada_name} : constant String := {self.value};"
        elif self.value.startswith('0x') or self.value.startswith('0X'):
            # Hexadecimal constant
            hex_value = int(self.value, 16)
            return f"   {ada_name} : constant := 16#{hex_value:X}#;"
        else:
            # Numeric constant
            try:
                int(self.value)
                return f"   {ada_name} : constant := {self.value};"
            except ValueError:
                # If not a number, treat as identifier
                return f"   {ada_name} : constant String := {self.value};"

    def _to_ada_name(self, config_name: str) -> str:
        """Convert CONFIG_FOO_BAR to Foo_Bar"""
        # Remove CONFIG_ prefix
        if config_name.startswith("CONFIG_"):
            name = config_name[7:]  # Remove "CONFIG_"
        else:
            name = config_name

        # Split by underscore and capitalize each word
        parts = name.split('_')
        ada_name = '_'.join(part.capitalize() for part in parts)

        return ada_name


def parse_autoconf(autoconf_path: Path) -> Dict[str, ConfigEntry]:
    """Parse autoconf.h and extract CONFIG_* definitions"""
    configs = {}

    # Regex patterns for different types of #define
    bool_pattern = re.compile(r'^\s*#define\s+(CONFIG_\w+)\s+1\s*$')
    value_pattern = re.compile(r'^\s*#define\s+(CONFIG_\w+)\s+(.+?)\s*$')

    with open(autoconf_path, 'r') as f:
        for line in f:
            line = line.strip()

            # Try boolean pattern first (CONFIG_FOO 1)
            match = bool_pattern.match(line)
            if match:
                name = match.group(1)
                configs[name] = ConfigEntry(name, "1", is_bool=True)
                continue

            # Try value pattern (CONFIG_FOO value)
            match = value_pattern.match(line)
            if match:
                name = match.group(1)
                value = match.group(2).strip()

                # Skip if it's already marked as boolean
                if name not in configs:
                    configs[name] = ConfigEntry(name, value, is_bool=False)

    return configs


def filter_ada_relevant_configs(configs: Dict[str, ConfigEntry]) -> List[ConfigEntry]:
    """Filter to configs relevant to Ada (start with CONFIG_ADA_ or commonly used ones)"""
    relevant = []

    # Prefixes to include
    include_prefixes = [
        'CONFIG_ADA_',           # Ada-specific configs
        'CONFIG_MAIN_STACK_',    # Main stack
        'CONFIG_IDLE_STACK_',    # Idle stack
        'CONFIG_ISR_STACK_',     # ISR stack
        'CONFIG_SYS_CLOCK_',     # System clock
        'CONFIG_NUM_IRQS',       # Number of IRQs
        'CONFIG_FLASH_',         # Flash memory
        'CONFIG_SRAM_',          # SRAM
    ]

    for name, entry in configs.items():
        # Include if matches any prefix
        if any(name.startswith(prefix) for prefix in include_prefixes):
            relevant.append(entry)
        # Or if it's a simple numeric constant that might be useful
        elif not entry.is_bool and not name.startswith('CONFIG_DT_'):
            # Skip device tree configs (too many, handled separately)
            continue

    return sorted(relevant, key=lambda e: e.name)


def generate_ada_package(configs: List[ConfigEntry], output_path: Path):
    """Generate Ada package with Kconfig constants"""

    # Package header
    content = [
        "--  SPDX-License-Identifier: Apache-2.0",
        "--",
        "--  Generated from Zephyr Kconfig - DO NOT EDIT MANUALLY",
        "--  This file is automatically generated by kconfig_to_ada.py",
        "",
        "package Zephyr.Config is",
        "",
        "   --  Zephyr Kconfig Parameters",
        "   --  These constants provide type-safe access to Zephyr configuration",
        "   --  without using C preprocessor directives",
        "",
    ]

    # Add constants
    if not configs:
        content.append("   --  No Ada-relevant configuration found")
    else:
        for entry in configs:
            content.append(entry.to_ada_constant())

    content.append("")

    # Add useful subtypes if we have relevant configs
    ada_specific = [c for c in configs if c.name.startswith('CONFIG_ADA_')]
    if ada_specific:
        content.extend([
            "   --  Type-safe subtypes derived from configuration",
            "",
        ])

        # Add subtypes for common ranges
        for entry in ada_specific:
            if "STACK_SIZE" in entry.name and not entry.is_bool:
                ada_name = entry._to_ada_name(entry.name)
                content.append(
                    f"   subtype Stack_Size_Type is Positive range 256 .. 65536;"
                )
                break

    # Package footer
    content.extend([
        "",
        "end Zephyr.Config;",
        ""
    ])

    # Write to file
    with open(output_path, 'w') as f:
        f.write('\n'.join(content))

    print(f"Generated Ada package: {output_path}")
    print(f"  Total configs: {len(configs)}")
    print(f"  Boolean configs: {sum(1 for c in configs if c.is_bool)}")
    print(f"  Value configs: {sum(1 for c in configs if not c.is_bool)}")


def main():
    parser = argparse.ArgumentParser(
        description='Convert Zephyr Kconfig (autoconf.h) to Ada package'
    )
    parser.add_argument(
        '--input',
        required=True,
        type=Path,
        help='Path to autoconf.h'
    )
    parser.add_argument(
        '--output',
        required=True,
        type=Path,
        help='Path to output Ada package (.ads file)'
    )
    parser.add_argument(
        '--all',
        action='store_true',
        help='Include all configs (not just Ada-relevant ones)'
    )

    args = parser.parse_args()

    # Check input file exists
    if not args.input.exists():
        print(f"Error: Input file not found: {args.input}", file=sys.stderr)
        return 1

    # Parse autoconf.h
    print(f"Parsing Kconfig from: {args.input}")
    all_configs = parse_autoconf(args.input)
    print(f"  Found {len(all_configs)} total configurations")

    # Filter to relevant configs (unless --all specified)
    if args.all:
        configs = list(all_configs.values())
    else:
        configs = filter_ada_relevant_configs(all_configs)

    print(f"  Selected {len(configs)} Ada-relevant configurations")

    # Generate Ada package
    args.output.parent.mkdir(parents=True, exist_ok=True)
    generate_ada_package(configs, args.output)

    return 0


if __name__ == '__main__':
    sys.exit(main())
