--  SPDX-License-Identifier: Apache-2.0
--
--  Generated from Zephyr Device Tree - DO NOT EDIT MANUALLY
--  This file is automatically generated by dt_to_ada.py

package Zephyr.Device_Tree is

   --  Hardware device properties from the board device tree.
   --  Use these constants to access device base addresses, IRQ numbers
   --  and clock frequencies from Ada code without C preprocessor macros.

   --  soc/interrupt-controller@af000000  --  arm,gic-v3, arm,gic
   package GIC is
      Base_Address : constant := 16#AF000000#;
      Size         : constant := 16#10000#;
   end GIC;

   --  soc/uart@9c090000  --  arm,pl011
   package UART0 is
      Base_Address : constant := 16#9C090000#;
      Size         : constant := 16#10000#;
      Interrupt    : constant := 0;
      IRQ_Priority : constant := 5;
   end UART0;

   --  soc/flash@88000000  --  soc-nv-flash
   package FLASH0 is
      Base_Address : constant := 16#88000000#;
      Size         : constant := 16#4000000#;
   end FLASH0;

   --  soc/memory@0  --  mmio-dram
   package DRAM0 is
      Base_Address : constant := 16#0#;
      Size         : constant := 16#8000000#;
   end DRAM0;

   --  apb-pclk  --  fixed-clock
   package UARTCLK is
      Clock_Freq   : constant := 24000000;
   end UARTCLK;

end Zephyr.Device_Tree;
