--
--  Copyright (c) 2025 Zephyr Ada Contributors
--
--  SPDX-License-Identifier: Apache-2.0
--

with Zephyr.Config;

package body Zephyr.Drivers.UART is

   --  System clock frequency from Kconfig (generated by kconfig_to_ada.py)
   Sys_Clock_Hz : constant := Zephyr.Config.Sys_Clock_Hw_Cycles_Per_Sec;

   procedure Initialize (Baud_Rate : Positive) is
      --  Compute baud rate divisor: SBR = Sys_Clock / (16 * Baud_Rate)
      SBR   : constant Natural := Sys_Clock_Hz / (16 * Baud_Rate);
      SBR_H : constant Natural := SBR / 256;  -- bits [12:8]
      SBR_L : constant Natural := SBR mod 256; -- bits [7:0]
   begin
      --  Disable TX/RX before changing baud rate
      UART0_Registers.C2 := (others => False);

      --  Set baud rate using type-safe record assignment (no shifts, no masks)
      UART0_Registers.BDH := (SBR => SBR_H, SBNS => False,
                               Reserved_1 => 0,
                               RXEDGIE => False, LBKDIE => False);
      UART0_Registers.BDL := (SBR => SBR_L);

      --  8-bit, no parity
      UART0_Registers.C1 := (PT => False, PE => False,
                              ILT => False, WAKE => False,
                              M => False, RSRC => False,
                              DOZEEN => False, LOOPS => False);

      --  Enable TX and RX
      UART0_Registers.C2 := (SBK => False, RWU => False,
                              RE => True, TE => True,
                              ILIE => False, RIE => False,
                              TCIE => False, TIE => False);
   end Initialize;

   procedure Put_Char (C : Character) is
   begin
      --  Wait for TX data register empty flag (TDRE = True means ready)
      loop
         exit when UART0_Registers.S1.TDRE;
      end loop;
      UART0_Registers.D := Character'Pos (C);
   end Put_Char;

   function Get_Char return Character is
   begin
      --  Wait for RX data register full flag (RDRF = True means data ready)
      loop
         exit when UART0_Registers.S1.RDRF;
      end loop;
      return Character'Val (UART0_Registers.D);
   end Get_Char;

end Zephyr.Drivers.UART;
