--  SPDX-License-Identifier: Apache-2.0
--
--  Generated from Zephyr Kconfig - DO NOT EDIT MANUALLY
--  This file is automatically generated by kconfig_to_ada.py

package Zephyr.Config is

   --  Zephyr Kconfig Parameters
   --  These constants provide type-safe access to Zephyr configuration
   --  without using C preprocessor directives

   Ada_Device_Tree_Package : constant Boolean := True;
   Ada_Interrupt_Handling : constant Boolean := True;
   Ada_Kconfig_Package : constant Boolean := True;
   Ada_Main_Stack_Size : constant := 4096;
   Ada_Max_Tasks : constant := 8;
   Ada_Secondary_Stack_Size : constant := 256;
   Ada_Task_Priority_Base : constant := 0;
   Ada_Task_Stack_Size : constant := 2048;
   Flash_Base_Address : constant := 16#0#;
   Flash_Load_Offset : constant := 16#0#;
   Flash_Load_Size : constant := 16#0#;
   Flash_Size : constant := 128;
   Idle_Stack_Size : constant := 256;
   Isr_Stack_Size : constant := 2048;
   Main_Stack_Size : constant := 1024;
   Num_Irqs : constant := 32;
   Sram_Base_Address : constant := 16#1FFFF000#;
   Sram_Offset : constant := 16#0#;
   Sram_Size : constant := 16;
   Sys_Clock_Exists : constant Boolean := True;
   Sys_Clock_Hw_Cycles_Per_Sec : constant := 48000000;
   Sys_Clock_Max_Timeout_Days : constant := 365;
   Sys_Clock_Ticks_Per_Sec : constant := 10000;

   --  Type-safe subtypes derived from configuration

   subtype Stack_Size_Type is Positive range 256 .. 65536;

end Zephyr.Config;
