--  SPDX-License-Identifier: Apache-2.0
--
--  Generated from Zephyr Device Tree - DO NOT EDIT MANUALLY
--  This file is automatically generated by dt_to_ada.py

package Zephyr.Device_Tree is

   --  Hardware device properties from the board device tree.
   --  Use these constants to access device base addresses, IRQ numbers
   --  and clock frequencies from Ada code without C preprocessor macros.

   --  soc/interrupt-controller@e000e100  --  arm,v6m-nvic
   package NVIC is
      Base_Address : constant := 16#E000E100#;
      Size         : constant := 16#C00#;
   end NVIC;

   --  soc/timer@e000e010  --  arm,armv6m-systick
   package SYSTICK is
      Base_Address : constant := 16#E000E010#;
      Size         : constant := 16#10#;
   end SYSTICK;

   --  soc/flash-controller@40020000/flash@0  --  soc-nv-flash
   package FLASH0 is
      Base_Address : constant := 16#0#;
      Size         : constant := 16#20000#;
   end FLASH0;

   --  soc/clock-controller@40064000  --  nxp,kinetis-mcg
   package MCG is
      Base_Address : constant := 16#40064000#;
      Size         : constant := 16#D#;
   end MCG;

   --  soc/i2c@40066000  --  nxp,kinetis-i2c
   package I2C0 is
      Base_Address : constant := 16#40066000#;
      Size         : constant := 16#1000#;
      Interrupt    : constant := 8;
      IRQ_Priority : constant := 0;
      Clock_Freq   : constant := 100000;
   end I2C0;

   --  soc/i2c@40066000/mma8451q@1d  --  nxp,fxos8700, nxp,mma8451q
   package MMA8451Q is
      --  No addressable properties
   end MMA8451Q;

   --  soc/rcm@4007f000  --  nxp,rcm-hwinfo
   package RCM is
      Base_Address : constant := 16#4007F000#;
      Size         : constant := 16#1000#;
   end RCM;

   --  soc/sim@40047000  --  nxp,kinetis-sim, nxp,sim-uuid
   package SIM is
      Base_Address : constant := 16#40047000#;
      Size         : constant := 16#1060#;
   end SIM;

   --  soc/uart@4006a000  --  nxp,kinetis-lpsci
   package UART0 is
      Base_Address : constant := 16#4006A000#;
      Size         : constant := 16#C#;
      Interrupt    : constant := 12;
      IRQ_Priority : constant := 0;
   end UART0;

   --  soc/adc@4003b000  --  nxp,kinetis-adc16
   package ADC0 is
      Base_Address : constant := 16#4003B000#;
      Size         : constant := 16#70#;
      Interrupt    : constant := 15;
      IRQ_Priority : constant := 0;
   end ADC0;

   --  soc/pinmux@40049000  --  nxp,port-pinmux
   package PORTA is
      Base_Address : constant := 16#40049000#;
      Size         : constant := 16#D0#;
   end PORTA;

   --  soc/pinmux@4004a000  --  nxp,port-pinmux
   package PORTB is
      Base_Address : constant := 16#4004A000#;
      Size         : constant := 16#D0#;
   end PORTB;

   --  soc/pinmux@4004b000  --  nxp,port-pinmux
   package PORTC is
      Base_Address : constant := 16#4004B000#;
      Size         : constant := 16#D0#;
   end PORTC;

   --  soc/pinmux@4004c000  --  nxp,port-pinmux
   package PORTD is
      Base_Address : constant := 16#4004C000#;
      Size         : constant := 16#D0#;
   end PORTD;

   --  soc/pinmux@4004d000  --  nxp,port-pinmux
   package PORTE is
      Base_Address : constant := 16#4004D000#;
      Size         : constant := 16#D0#;
   end PORTE;

   --  soc/gpio@400ff000  --  nxp,kinetis-gpio
   package GPIOA is
      Base_Address : constant := 16#400FF000#;
      Size         : constant := 16#40#;
      Interrupt    : constant := 30;
      IRQ_Priority : constant := 2;
   end GPIOA;

   --  soc/gpio@400ff040  --  nxp,kinetis-gpio
   package GPIOB is
      Base_Address : constant := 16#400FF040#;
      Size         : constant := 16#40#;
   end GPIOB;

   --  soc/gpio@400ff0c0  --  nxp,kinetis-gpio
   package GPIOD is
      Base_Address : constant := 16#400FF0C0#;
      Size         : constant := 16#40#;
      Interrupt    : constant := 31;
      IRQ_Priority : constant := 2;
   end GPIOD;

   --  soc/usbd@40072000  --  nxp,kinetis-usbd
   package ZEPHYR_UDC0 is
      Base_Address : constant := 16#40072000#;
      Size         : constant := 16#1000#;
      Interrupt    : constant := 24;
      IRQ_Priority : constant := 1;
   end ZEPHYR_UDC0;

   --  cpus/cpu@0  --  arm,cortex-m0+
   package CPU0 is
      Clock_Freq   : constant := 48000000;
   end CPU0;

   --  memory@1ffff000  --  mmio-sram
   package SRAM0 is
      Base_Address : constant := 16#1FFFF000#;
      Size         : constant := 16#4000#;
   end SRAM0;

   --  pinctrl  --  nxp,port-pinctrl
   package PINCTRL is
      --  No addressable properties
   end PINCTRL;

   --  pinctrl/adc0_default
   package ADC0_DEFAULT is
      --  No addressable properties
   end ADC0_DEFAULT;

   --  pinctrl/i2c0_default
   package I2C0_DEFAULT is
      --  No addressable properties
   end I2C0_DEFAULT;

   --  pinctrl/uart0_default
   package UART0_DEFAULT is
      --  No addressable properties
   end UART0_DEFAULT;

   --  leds/led_0
   package RED_LED is
      --  No addressable properties
   end RED_LED;

   --  leds/led_1
   package GREEN_LED is
      --  No addressable properties
   end GREEN_LED;

   --  leds/led_2
   package BLUE_LED is
      --  No addressable properties
   end BLUE_LED;

   --  gpio_keys/button_0
   package USER_BUTTON_0 is
      --  No addressable properties
   end USER_BUTTON_0;

   --  gpio_keys/button_1
   package USER_BUTTON_1 is
      --  No addressable properties
   end USER_BUTTON_1;

   --  connector  --  arduino-header-r3
   package ARDUINO_HEADER is
      --  No addressable properties
   end ARDUINO_HEADER;

end Zephyr.Device_Tree;
