/* Configuration for ada_protected_demo generated by Alire */
#ifndef ADA_PROTECTED_DEMO_CONFIG_H
#define ADA_PROTECTED_DEMO_CONFIG_H

#define CRATE_VERSION "0.1.0"
#define CRATE_NAME "ada_protected_demo"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
